DROP TABLE IF EXISTS emails;
CREATE TABLE emails (
	sender TEXT NOT NULL PRIMARY KEY,
	count INTEGER DEFAULT 20,
	created TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
	modified TIMESTAMP DEFAULT CURRENT_TIMESTAMP
);
